spring:
  application.name: TechTrack
  datasource:
    username: tracker
    password:
    url: jdbc:postgres://tracker:XhjdKc3dAEsr8OLzUVGk4GBaiiB1DwVc@dpg-codne4i0si5c73940pa0-a/trackdb_si57
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

